### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach() in

### ISSUE THREAD

**Issue by bari86** [littlebizzy/slickstack#172] opened 2022-08-16 14:26 UTC
A newly installed SS would show this error. Not sure why.

`[15-Aug-2022 13:15:45 UTC] PHP Warning:  Invalid argument supplied for foreach() in /var/www/html/wp-admin/includes/plugin.php on line 1779`

**Comment by jessuppi** [comment] 2022-08-17 10:07
Duplicate of https://github.com/littlebizzy/slickstack/issues/30

**Closed by jessuppi** 2022-08-17 10:07 UTC
