### ISSUE TITLE
Hide Cloudflare API

### ISSUE THREAD

**Issue by bari86** [littlebizzy/slickstack#170] opened 2022-08-16 09:25 UTC
When we view the cloudflare plugin, the Cloudflare API and Cloudflare email is clearly visible. Can all this information be encrypted and hidden after the initial install? Or else, can this plugin have option to be installed/not installed during the ss-install wizard?

**Comment by jessuppi** [comment] 2022-08-17 10:08
Duplicate of https://github.com/littlebizzy/slickstack/issues/126

**Closed by jessuppi** 2022-08-17 10:08 UTC
